import { use } from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import WhatsAppButton from '@/components/WhatsAppButton';
import ServiceDetail from './ServiceDetail';

// Static service data for SSR
const allServices = {
  'web-development': { title: 'Web Development', icon: '🌐', category: 'Development', color: '#7c3aed', shortDescription: 'Custom websites built with modern technologies for performance and scalability.', description: 'We create stunning, high-performance websites using the latest technologies including React, Next.js, and Node.js. Our websites are built with SEO optimization, responsive design, and blazing-fast performance in mind.', features: [{ title: 'Custom Design', description: 'Unique designs tailored to your brand identity' }, { title: 'Responsive Layout', description: 'Perfect experience on all devices and screen sizes' }, { title: 'SEO Optimized', description: 'Built-in search engine optimization for better rankings' }, { title: 'Fast Performance', description: 'Optimized loading speeds for better user experience' }, { title: 'CMS Integration', description: 'Easy content management with modern CMS solutions' }, { title: 'Analytics Setup', description: 'Track your visitors and conversions effectively' }], pricing: { startingAt: '₹25,000', note: 'Price varies based on complexity' } },
  'app-development': { title: 'App Development', icon: '📱', category: 'Development', color: '#3b82f6', shortDescription: 'Native and cross-platform mobile apps that users love.', description: 'Build powerful mobile applications for iOS and Android using React Native and Flutter. We focus on creating intuitive user experiences with smooth animations.', features: [{ title: 'Cross-Platform', description: 'One codebase for iOS and Android' }, { title: 'Native Performance', description: 'Smooth, native-like experience' }, { title: 'Push Notifications', description: 'Engage users with timely notifications' }, { title: 'Offline Support', description: 'App works even without internet' }, { title: 'App Store Deployment', description: 'Complete submission and approval process' }, { title: 'Analytics & Tracking', description: 'Monitor user behavior and performance' }], pricing: { startingAt: '₹50,000', note: 'Based on features and platforms' } },
  'saas-development': { title: 'SaaS Development', icon: '☁️', category: 'Development', color: '#6366f1', shortDescription: 'Scalable SaaS platforms built for growth.', description: 'Transform your idea into a fully functional SaaS product with multi-tenant architecture, subscription management, and scalable infrastructure.', features: [{ title: 'Multi-tenant Architecture', description: 'Serve multiple clients from one codebase' }, { title: 'Subscription Management', description: 'Stripe/Razorpay integration for billing' }, { title: 'User Management', description: 'Roles, permissions, and team management' }, { title: 'API Design', description: 'RESTful APIs for third-party integrations' }, { title: 'Auto-scaling', description: 'Infrastructure that grows with your users' }, { title: 'Dashboard', description: 'Admin dashboards with real-time metrics' }], pricing: { startingAt: '₹1,00,000', note: 'Comprehensive SaaS solutions' } },
  'admin-dashboards': { title: 'Admin Dashboards', icon: '📊', category: 'Development', color: '#8b5cf6', shortDescription: 'Powerful admin panels for data-driven decisions.', description: 'Custom admin dashboards with real-time analytics, data visualization, user management, and workflow automation tools.', features: [{ title: 'Real-time Data', description: 'Live updates and real-time analytics' }, { title: 'Data Visualization', description: 'Charts, graphs, and interactive reports' }, { title: 'Role-based Access', description: 'Control permissions granularly' }, { title: 'Export & Reports', description: 'Generate PDF/Excel reports' }, { title: 'Notification System', description: 'Alerts for important events' }, { title: 'Mobile Responsive', description: 'Manage from any device' }], pricing: { startingAt: '₹30,000', note: 'Custom dashboard solutions' } },
  'ai-chatbots': { title: 'AI Chatbots', icon: '🤖', category: 'AI & Automation', color: '#10b981', shortDescription: 'Intelligent chatbots that handle queries 24/7.', description: 'Deploy AI-powered chatbots using GPT-4, LangChain, and custom ML models for customer support, lead qualification, and sales.', features: [{ title: 'Natural Language Processing', description: 'Understand natural language queries' }, { title: 'Multi-platform', description: 'Website, WhatsApp, social media' }, { title: 'Custom Training', description: 'Train on your business data' }, { title: 'Lead Capture', description: 'Automatically qualify leads' }, { title: 'Human Handoff', description: 'Transfer to agents when needed' }, { title: 'Analytics', description: 'Track and improve over time' }], pricing: { startingAt: '₹40,000', note: 'Custom AI chatbot solutions' } },
  'automation-systems': { title: 'Automation Systems', icon: '⚡', category: 'AI & Automation', color: '#f59e0b', shortDescription: 'Automate repetitive tasks and streamline workflows.', description: 'Intelligent automation using Make, Zapier, and custom scripts to connect apps and save hundreds of hours per month.', features: [{ title: 'Workflow Automation', description: 'Automate complex processes' }, { title: 'App Integration', description: 'Connect 500+ apps' }, { title: 'Data Sync', description: 'Keep data consistent' }, { title: 'Email Automation', description: 'Automated sequences' }, { title: 'Report Generation', description: 'Auto-generate reports' }, { title: 'Error Handling', description: 'Smart error recovery' }], pricing: { startingAt: '₹20,000', note: 'Per automation workflow' } },
  'custom-ai-tools': { title: 'Custom AI Tools', icon: '🧠', category: 'AI & Automation', color: '#7c3aed', shortDescription: 'Bespoke AI solutions for unique business needs.', description: 'Custom AI tools from document processing to predictive analytics, leveraging the latest AI technologies.', features: [{ title: 'Custom Models', description: 'AI models on your specific data' }, { title: 'Document Processing', description: 'Extract data from documents' }, { title: 'Predictive Analytics', description: 'Forecast trends accurately' }, { title: 'Image Recognition', description: 'Computer vision solutions' }, { title: 'Recommendation Engine', description: 'Personalized recommendations' }, { title: 'API Integration', description: 'Easy system integration' }], pricing: { startingAt: '₹60,000', note: 'Custom AI development' } },
  'llm-integration': { title: 'LLM Integration', icon: '💬', category: 'AI & Automation', color: '#06b6d4', shortDescription: 'Integrate large language models into your apps.', description: 'Harness GPT-4, Claude, Gemini with RAG systems, fine-tuning, semantic search, and AI-powered features.', features: [{ title: 'RAG Systems', description: 'Accurate retrieval-augmented answers' }, { title: 'Fine-tuning', description: 'Custom model training' }, { title: 'Semantic Search', description: 'AI-powered contextual search' }, { title: 'Content Generation', description: 'Automated content creation' }, { title: 'Multi-model', description: 'Best model per task' }, { title: 'Cost Optimization', description: 'Efficient API usage' }], pricing: { startingAt: '₹45,000', note: 'LLM integration projects' } },
  'ui-ux-design': { title: 'UI/UX Design', icon: '🎨', category: 'Design', color: '#ec4899', shortDescription: 'User-centered designs that convert visitors.', description: 'Exceptional user experiences combining research, wireframing, prototyping, and visual design.', features: [{ title: 'User Research', description: 'Understand user needs' }, { title: 'Wireframing', description: 'Blueprint your application' }, { title: 'Prototyping', description: 'Interactive prototypes' }, { title: 'Visual Design', description: 'Stunning visual designs' }, { title: 'Design System', description: 'Consistent design language' }, { title: 'Usability Testing', description: 'Validate with real users' }], pricing: { startingAt: '₹15,000', note: 'Per project basis' } },
  'branding': { title: 'Branding', icon: '✨', category: 'Design', color: '#f43f5e', shortDescription: 'Build a memorable brand identity.', description: 'Powerful brand identity from logo to guidelines, color palettes to typography.', features: [{ title: 'Logo Design', description: 'Unique, memorable logos' }, { title: 'Brand Guidelines', description: 'Comprehensive style guide' }, { title: 'Color Palette', description: 'Strategic color selection' }, { title: 'Typography', description: 'Font selection guidelines' }, { title: 'Brand Collateral', description: 'Cards, letterheads, etc.' }, { title: 'Social Templates', description: 'Branded social templates' }], pricing: { startingAt: '₹20,000', note: 'Complete branding packages' } },
  'landing-pages': { title: 'Landing Pages', icon: '🚀', category: 'Design', color: '#7c3aed', shortDescription: 'High-converting landing pages.', description: 'Design and develop landing pages that convert with compelling copy and optimization.', features: [{ title: 'Conversion Focused', description: 'Maximize conversions' }, { title: 'A/B Testing', description: 'Test variations' }, { title: 'Fast Loading', description: 'Optimized performance' }, { title: 'Mobile First', description: 'Perfect on every screen' }, { title: 'Analytics', description: 'Track every visitor' }, { title: 'Lead Capture', description: 'Effective forms and CTAs' }], pricing: { startingAt: '₹10,000', note: 'Per landing page' } },
  'product-design': { title: 'Product Design', icon: '💎', category: 'Design', color: '#8b5cf6', shortDescription: 'End-to-end product design.', description: 'Full-cycle product design from ideation to launch with strategy, user flows, and prototypes.', features: [{ title: 'Product Strategy', description: 'Vision and roadmap' }, { title: 'User Flows', description: 'Complete user journeys' }, { title: 'Interface Design', description: 'Beautiful interfaces' }, { title: 'Prototyping', description: 'Clickable prototypes' }, { title: 'Design Handoff', description: 'Developer-ready specs' }, { title: 'Iteration', description: 'Continuous improvement' }], pricing: { startingAt: '₹35,000', note: 'Full product design' } },
  'seo-optimization': { title: 'SEO Optimization', icon: '🔍', category: 'Marketing', color: '#10b981', shortDescription: 'Rank higher on Google.', description: 'Comprehensive SEO including technical SEO, content optimization, link building, and local SEO.', features: [{ title: 'Technical SEO', description: 'Fix ranking issues' }, { title: 'Keyword Research', description: 'Find high-value keywords' }, { title: 'Content Optimization', description: 'Optimize for search' }, { title: 'Link Building', description: 'Quality backlinks' }, { title: 'Local SEO', description: 'Dominate local results' }, { title: 'Monthly Reports', description: 'Performance reports' }], pricing: { startingAt: '₹15,000/mo', note: 'Monthly retainer' } },
  'performance-marketing': { title: 'Performance Marketing', icon: '📊', category: 'Marketing', color: '#3b82f6', shortDescription: 'Data-driven ad campaigns.', description: 'High-performance campaigns across Google, Facebook, Instagram, LinkedIn with advanced targeting.', features: [{ title: 'Google Ads', description: 'Search, display, shopping' }, { title: 'Social Media Ads', description: 'Facebook, Instagram, LinkedIn' }, { title: 'Retargeting', description: 'Bring back visitors' }, { title: 'A/B Testing', description: 'Optimize ad creatives' }, { title: 'Conversion Tracking', description: 'Track every conversion' }, { title: 'ROI Reports', description: 'Clear ad spend reporting' }], pricing: { startingAt: '₹20,000/mo', note: 'Plus ad spend' } },
  'social-media-management': { title: 'Social Media Management', icon: '📱', category: 'Marketing', color: '#ec4899', shortDescription: 'Build your social presence.', description: 'Creating engaging content, managing accounts, and growing your following across all platforms.', features: [{ title: 'Content Creation', description: 'Posts, reels, stories' }, { title: 'Community Management', description: 'Respond to engagement' }, { title: 'Growth Strategy', description: 'Organic growth tactics' }, { title: 'Influencer Outreach', description: 'Connect with influencers' }, { title: 'Content Calendar', description: 'Consistent posting' }, { title: 'Analytics', description: 'Growth metrics' }], pricing: { startingAt: '₹12,000/mo', note: 'Per platform' } },
  'content-strategy': { title: 'Content Strategy', icon: '✍️', category: 'Marketing', color: '#f59e0b', shortDescription: 'Strategic content that converts.', description: 'Comprehensive content strategy with planning, creation, distribution, and analysis.', features: [{ title: 'Content Audit', description: 'Analyze existing content' }, { title: 'Strategy Planning', description: 'Data-driven roadmap' }, { title: 'Blog Writing', description: 'SEO-optimized posts' }, { title: 'Email Marketing', description: 'Newsletter content' }, { title: 'Video Scripts', description: 'Video content scripts' }, { title: 'Performance', description: 'Measure content ROI' }], pricing: { startingAt: '₹18,000/mo', note: 'Content packages' } },
  'api-integration': { title: 'API Integration', icon: '🔗', category: 'Other Services', color: '#06b6d4', shortDescription: 'Connect systems with APIs.', description: 'Seamlessly integrate third-party APIs from payment gateways to CRM systems.', features: [{ title: 'REST & GraphQL', description: 'Any API type' }, { title: 'Payment APIs', description: 'Stripe, Razorpay, PayPal' }, { title: 'CRM Integration', description: 'Salesforce, HubSpot' }, { title: 'Cloud Services', description: 'AWS, GCP, Azure' }, { title: 'Webhook Setup', description: 'Event-driven integrations' }, { title: 'Documentation', description: 'Complete API docs' }], pricing: { startingAt: '₹15,000', note: 'Per integration' } },
  'firebase-setup': { title: 'Firebase Setup', icon: '🔥', category: 'Other Services', color: '#f59e0b', shortDescription: 'Complete Firebase configuration.', description: 'Full Firebase setup including authentication, Firestore, storage, functions, and notifications.', features: [{ title: 'Authentication', description: 'Multiple auth providers' }, { title: 'Firestore', description: 'Real-time database' }, { title: 'Cloud Storage', description: 'File uploads' }, { title: 'Cloud Functions', description: 'Serverless logic' }, { title: 'Push Notifications', description: 'FCM setup' }, { title: 'Security Rules', description: 'Proper security' }], pricing: { startingAt: '₹12,000', note: 'Firebase configuration' } },
  'payment-gateway-integration': { title: 'Payment Gateway Integration', icon: '💳', category: 'Other Services', color: '#10b981', shortDescription: 'Secure payment processing.', description: 'Integrate Razorpay, Stripe, PayPal for smooth, secure transactions.', features: [{ title: 'Multiple Gateways', description: 'Razorpay, Stripe, PayPal' }, { title: 'Subscriptions', description: 'Recurring payments' }, { title: 'Invoicing', description: 'Auto-generated invoices' }, { title: 'Refunds', description: 'Easy refund processing' }, { title: 'Analytics', description: 'Revenue tracking' }, { title: 'PCI Compliance', description: 'Secure processing' }], pricing: { startingAt: '₹10,000', note: 'Per gateway' } },
  'website-maintenance': { title: 'Website Maintenance', icon: '🛠️', category: 'Other Services', color: '#7c3aed', shortDescription: 'Keep your site running smoothly.', description: 'Updates, security patches, performance optimization, backups, and content updates.', features: [{ title: 'Regular Updates', description: 'Software and plugins' }, { title: 'Security', description: 'Threat protection' }, { title: 'Performance', description: 'Speed optimization' }, { title: 'Backups', description: 'Automated backups' }, { title: 'Content Updates', description: 'Update as needed' }, { title: 'Uptime Monitoring', description: '24/7 monitoring' }], pricing: { startingAt: '₹5,000/mo', note: 'Monthly plans' } },
};

export function generateStaticParams() {
  return Object.keys(allServices).map((slug) => ({ slug }));
}

export async function generateMetadata({ params }) {
  const { slug } = await params;
  const service = allServices[slug];
  if (!service) return { title: 'Service Not Found — NexusDigital' };
  return {
    title: `${service.title} — NexusDigital`,
    description: service.shortDescription,
  };
}

export default function ServicePage({ params }) {
  const { slug } = use(params);
  const service = allServices[slug];
  
  return (
    <>
      <Navbar />
      <main>
        <ServiceDetail service={service} slug={slug} />
      </main>
      <Footer />
      <WhatsAppButton />
    </>
  );
}
